/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import util.UtilBD;

/**
 *
 * @author Isaac Herrera
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgRegistro = new javax.swing.JDialog();
        pnlRegistro = new javax.swing.JPanel();
        lblRegistro = new com.xzq.osc.JocLabel();
        txtPasswordRegistro = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRectBackground();
        btnSalir = new com.xzq.osc.JocLabel();
        txtPasswordRegistro1 = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        btnRegistrar = new org.jdesktop.swingx.JXButton();
        txtUsuarioRegistro = new org.edisoncor.gui.textField.TextFieldRectBackground();
        pnlPrincipal = new javax.swing.JPanel();
        lblLogin = new com.xzq.osc.JocLabel();
        txtPassword = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        txtUsuario = new org.edisoncor.gui.textField.TextFieldRectBackground();
        btnEntrar = new org.jdesktop.swingx.JXButton();
        btnRegistro = new org.jdesktop.swingx.JXHyperlink();
        btnSalirSistema = new com.xzq.osc.JocLabel();

        dlgRegistro.setMinimumSize(new java.awt.Dimension(800, 600));
        dlgRegistro.setModal(true);
        dlgRegistro.setUndecorated(true);
        dlgRegistro.setLocationRelativeTo(this);

        pnlRegistro.setBackground(new java.awt.Color(255, 255, 255));

        lblRegistro.setAntialias(true);
        lblRegistro.setText("Registro");
        lblRegistro.setFont(new java.awt.Font("Roboto Thin", 0, 48)); // NOI18N

        txtPasswordRegistro.setCaretColor(new java.awt.Color(153, 153, 153));
        txtPasswordRegistro.setColorDeBorde(new java.awt.Color(255, 255, 255));
        txtPasswordRegistro.setDescripcion("Repite contraseña");
        txtPasswordRegistro.setEchoChar('x');
        txtPasswordRegistro.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N

        txtNombre.setCaretColor(new java.awt.Color(204, 204, 204));
        txtNombre.setColorDeBorde(new java.awt.Color(255, 255, 255));
        txtNombre.setDescripcion("Nombre");
        txtNombre.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N

        btnSalir.setAntialias(true);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setText("X");
        btnSalir.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        txtPasswordRegistro1.setCaretColor(new java.awt.Color(153, 153, 153));
        txtPasswordRegistro1.setColorDeBorde(new java.awt.Color(255, 255, 255));
        txtPasswordRegistro1.setDescripcion("Contraseña");
        txtPasswordRegistro1.setEchoChar('x');
        txtPasswordRegistro1.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N

        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        btnRegistrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtUsuarioRegistro.setCaretColor(new java.awt.Color(204, 204, 204));
        txtUsuarioRegistro.setColorDeBorde(new java.awt.Color(255, 255, 255));
        txtUsuarioRegistro.setDescripcion("Usuario");
        txtUsuarioRegistro.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswordRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        dlgRegistro.getContentPane().add(pnlRegistro, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión | Polish");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblLogin.setAntialias(true);
        lblLogin.setText("Polish");
        lblLogin.setFont(new java.awt.Font("Roboto Thin", 0, 48)); // NOI18N

        txtPassword.setCaretColor(new java.awt.Color(153, 153, 153));
        txtPassword.setColorDeBorde(new java.awt.Color(255, 255, 255));
        txtPassword.setDescripcion("Contraseña");
        txtPassword.setEchoChar('x');
        txtPassword.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N

        txtUsuario.setCaretColor(new java.awt.Color(204, 204, 204));
        txtUsuario.setColorDeBorde(new java.awt.Color(255, 255, 255));
        txtUsuario.setDescripcion("Usuario");
        txtUsuario.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N

        btnEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnEntrar.setText("Entrar");
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        btnEntrar.setCursor(new Cursor(Cursor.HAND_CURSOR));

        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("Crear una cuenta");
        btnRegistro.setClickedColor(new java.awt.Color(153, 153, 153));
        btnRegistro.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnSalirSistema.setAntialias(true);
        btnSalirSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalirSistema.setText("X");
        btnSalirSistema.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        btnSalirSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirSistemaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalirSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalirSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        dlgRegistro.setVisible(true);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        dlgRegistro.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirSistemaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirSistemaMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (UtilBD.crearUsuario(txtNombre.getText(), txtPasswordRegistro1.getPassword().toString(), txtUsuarioRegistro.getText())) {
            JOptionPane.showMessageDialog(this, "Agregado");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnEntrar;
    private org.jdesktop.swingx.JXButton btnRegistrar;
    private org.jdesktop.swingx.JXHyperlink btnRegistro;
    private com.xzq.osc.JocLabel btnSalir;
    private com.xzq.osc.JocLabel btnSalirSistema;
    private javax.swing.JDialog dlgRegistro;
    private com.xzq.osc.JocLabel lblLogin;
    private com.xzq.osc.JocLabel lblRegistro;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlRegistro;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtNombre;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground txtPassword;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground txtPasswordRegistro;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground txtPasswordRegistro1;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtUsuario;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
